<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net48;net8.0</TargetFrameworks>
		<RootNamespace>NH.Bencher</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<None Update="hibernate.cfg.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<EmbeddedResource Include="EntityMappings/*.hbm.xml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Antlr3.Runtime" Version="3.5.1" />
		<PackageReference Include="Iesi.Collections" Version="4.0.5" />
		<PackageReference Include="NHibernate" Version="5.4.7" />
		<PackageReference Include="Remotion.Linq" Version="2.2.0" />
		<PackageReference Include="Remotion.Linq.EagerFetching" Version="2.2.0" />
	</ItemGroup>
</Project>