<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net48;net8.0</TargetFrameworks>
		<RootNamespace>NH.Bencher</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<None Update="hibernate.cfg.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<EmbeddedResource Include="EntityMappings/*.hbm.xml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Antlr3.Runtime" />
		<PackageReference Include="Iesi.Collections" />
		<PackageReference Include="NHibernate" />
		<PackageReference Include="Remotion.Linq" />
		<PackageReference Include="Remotion.Linq.EagerFetching" />
	</ItemGroup>
</Project>