<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net48;net8.0</TargetFrameworks>
		<RootNamespace>NH.Bencher</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Iesi.Collections" Version="4.0.5" />
		<PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
	</ItemGroup>
</Project>